language: node_js
node_js:
  - "6"

services:
  - docker

cache:
directories:
  - /var/lib/docker

before_install:
  - npm install -g gulp bower node-gyp
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - npm install && bower install

script:
  - npm test
  - gulp build
  - docker build -t web-service .

after_success:
  - eval "$(~/.local/bin/aws ecr get-login)"
  - docker tag web-service:latest 277555456074.dkr.ecr.eu-west-1.amazonaws.com/web-service:build-$TRAVIS_BUILD_NUMBER
  - docker tag web-service:latest 277555456074.dkr.ecr.eu-west-1.amazonaws.com/web-service:integration-tested
  - docker push 277555456074.dkr.ecr.eu-west-1.amazonaws.com/web-service:build-$TRAVIS_BUILD_NUMBER
  - docker push 277555456074.dkr.ecr.eu-west-1.amazonaws.com/web-service:integration-tested
  # Trigger integration pipeline
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo $DEPLOY_KEY | base64 -d > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa # this key should have push access
  - ssh-add ~/.ssh/id_rsa
  - git clone git@github.com:Kamshak/ba-microservices-integration.git integration
  - export SERVICE_NAME=$(basename `git rev-parse --show-toplevel`)
  - cd integration
  - sed -i "/webServiceTag/c\webServiceTag = \"build-$TRAVIS_BUILD_NUMBER\"" values.toml # Update version number
  - git add .
  - git commit -m "Trigger integration from $SERVICE_NAME, Travis Build $TRAVIS_JOB_NUMBER, Commit $TRAVIS_COMMIT"
  - git push origin master
